### ISSUE TITLE
Stuck on: Downloading: Bootstrap

### ISSUE THREAD

**Issue by Newkz** [MCUpdater/MCU-Bootstrap#7]
I've compiled from jdk1.8.0_221 on Windows 10

I followed the instruction on: https://github.com/MCUpdater/workspace

I add the Forge Installers to their respective folders (and rename them)
_By the way, you should add this step to your instruction, took me an eternity to figure out this had to be done._

I run the commands as instructed

```
gradlew setupWorkspace
gradlew clean build gatherArtifacts
```
And then i run the build file: MCU-Bootstrap.jar

But it just gets stuck like this: https://i.imgur.com/Beq7hzl.png

There are no logs in the .MCUpdater folder, so not sure how I can provide more to describe the situtation. 
I don't get this problem when I run the bootstrap build from: http://files.mcupdater.com/

**Comment by smbarbour** [comment]
Issue corrected in repository

**Comment by Newkz** [comment]
Unfortunately, this did not seem to fix the problem, I'm still getting stuck at 

> Downloading: Bootstrap

Thanks for adding the instruction in the readme though.

**Comment by smbarbour** [comment]
Make sure that you do a git pull on the MCU-DownloadLib repository

**Comment by Newkz** [comment]
I removed the whole workspace and redid the steps in the instructions. And just to be sure I did a git pull for MCU-DownloadLib. Unfortunately it did not help.

I tried installing jdk8 32bit, and compile it with that. But then the MCU-Bootstrap splash screen just never showing up and the javaw.exe closed shortly after.

During compilation though, there is a warning, no clue if it's relevant:
`warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning`

I've tried all this on 2 Windows 10 PC's with the same results

-----------------

I just ran it through bash shell and powershell as Admin by using `java -jar ./MCU-Bootstrap.jar` which made it work. But not very useful if I need to share the jar, it's not very simple to run jar's for the average user.

**Comment by Newkz** [comment]
If I open cmd and use `java -jar ./MCU-Bootstrap.jar` I get the following error.

`Microsoft Windows [Version 10.0.17134.885]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\d60user>cd Desktop

C:\Users\d60user\Desktop>java -jar ./MCU-Bootstrap.jar
MCUpdater Bootstrap 1.3
System.getProperty('os.name') == 'Windows 10'
System.getProperty('os.version') == '10.0'
System.getProperty('os.arch') == 'amd64'
System.getProperty('java.version') == '1.8.0_221'
System.getProperty('java.vendor') == 'Oracle Corporation'
System.getProperty('sun.arch.data.model') == '64'
Registered root certificate: dst_root_ca_x3
Registered root certificate: startssl
@ verisignclass2g2ca [jdk]
@ digicertassuredidg3 [jdk]
@ verisignuniversalrootca [jdk]
@ digicerttrustedrootg4 [jdk]
@ identrustpublicca [jdk]
@ utnuserfirstobjectca [jdk]
@ geotrustuniversalca [jdk]
@ digicertglobalrootg3 [jdk]
@ entrustrootcaec1 [jdk]
@ secomscrootca1 [jdk]
@ globalsignr2ca [jdk]
@ identrustdstx3 [jdk]
@ comodoeccca [jdk]
@ globalsignrootcar6 [jdk]
@ entrust2048ca [jdk]
@ addtrustexternalca [jdk]
@ globalsigneccrootcar4 [jdk]
@ usertrustrsaca [jdk]
@ digicertassuredidrootca [jdk]
@ digicertglobalrootg2 [jdk]
@ actalisauthenticationrootca [jdk]
@ digicertassuredidg2 [jdk]
@ swisssigngoldg2ca [jdk]
@ entrustrootcag2 [jdk]
@ quovadisrootca2g3 [jdk]
@ securetrustca [jdk]
@ camerfirmachambersca [jdk]
@ geotrustprimaryca [jdk]
@ identrustcommercial [jdk]
@ thawteprimaryrootcag3 [jdk]
@ buypassclass3ca [jdk]
@ verisigntsaca [jdk]
@ verisignclass3g4ca [jdk]
@ baltimorecybertrustca [jdk]
@ gtecybertrustglobalca [jdk]
@ luxtrustglobalrootca [jdk]
@ verisignclass3g2ca [jdk]
@ camerfirmachamberscommerceca [jdk]
@ soneraclass2ca [jdk]
@ affirmtrustnetworkingca [jdk]
@ ttelesecglobalrootclass3ca [jdk]
@ xrampglobalca [jdk]
@ geotrustprimarycag3 [jdk]
@ camerfirmachambersignca [jdk]
@ thawteprimaryrootcag2 [jdk]
@ usertrusteccca [jdk]
@ dst_root_ca_x3
@ swisssignsilverg2ca [jdk]
@ affirmtrustpremiumca [jdk]
@ globalsignca [jdk]
@ dtrustclass3ca2 [jdk]
@ affirmtrustcommercialca [jdk]
@ letsencryptisrgx1 [jdk]
@ thawtepremiumserverca [jdk]
@ comodoaaaca [jdk]
@ geotrustprimarycag2 [jdk]
@ globalsignr3ca [jdk]
@ thawteprimaryrootca [jdk]
@ quovadisrootca3 [jdk]
@ starfieldclass2ca [jdk]
@ starfieldrootg2ca [jdk]
@ verisignclass3ca [jdk]
@ affirmtrustpremiumeccca [jdk]
@ geotrustglobalca [jdk]
@ swisscomrootca2 [jdk]
@ godaddyclass2ca [jdk]
@ godaddyrootg2ca [jdk]
@ verisignclass3g5ca [jdk]
@ certumca [jdk]
@ quovadisrootca2 [jdk]
@ swisssignplatinumg2ca [jdk]
@ chunghwaepkirootca [jdk]
@ quovadisrootca3g3 [jdk]
@ quovadisrootca [jdk]
@ addtrustclass1ca [jdk]
@ digicerthighassuranceevrootca [jdk]
@ startssl
@ quovadisrootca1g3 [jdk]
@ comodorsaca [jdk]
@ keynectisrootca [jdk]
@ buypassclass2ca [jdk]
@ secomscrootca2 [jdk]
@ entrustevca [jdk]
@ verisignclass3g3ca [jdk]
@ certumtrustednetworkca [jdk]
@ teliasonerarootcav1 [jdk]
@ dtrustclass3ca2ev [jdk]
@ globalsigneccrootcar5 [jdk]
@ starfieldservicesrootg2ca [jdk]
@ ttelesecglobalrootclass2ca [jdk]
@ addtrustqualifiedca [jdk]
@ digicertglobalrootca [jdk]

Iterating defined distributions:
Release - MCUpdater 3.4.12
--1.8
Downloading:
MCUpdater.jar - Started
MCUpdater.jar - Hash matches - No download
Downloading:
MCU-API.jar - Started
MCU-API.jar - Hash matches - No download
Downloading:
MCU-Launcher.jar - Started
MCU-Launcher.jar - Hash matches - No download
Downloading:
MCU-ForgeLoader.jar - Started
MCU-ForgeLoader.jar - Hash matches - No download
Downloading:
MCU-LegacyForgeLoader.jar - Started
java.io.IOException: Cannot run program "C:\Program Files\Java\jre1.8.0_221\bin\java": CreateProcess error=740, The requested operation requires elevationMCU-LegacyForgeLoader.jar - Hash matches - No download

Downloading:    at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)

MCU-DownloadLib.jar - Started
        at java.lang.Runtime.exec(Unknown Source)MCU-DownloadLib.jar - Hash matches - No download

        at org.mcupdater.BootstrapForm.onQueueFinished(BootstrapForm.java:326)Downloading:

commons-codec-1.9.jar - Started at org.mcupdater.downloadlib.DownloadQueue.processQueue(DownloadQueue.java:116)

        at org.mcupdater.BootstrapForm.doWork(BootstrapForm.java:188)
        at org.mcupdater.BootstrapForm$1.run(BootstrapForm.java:128)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
commons-codec-1.9.jar - Hash matches - No download
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
Downloading:
        at java.awt.EventQueue.access$500(Unknown Source)
commons-io-2.4.jar - Started
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
commons-io-2.4.jar - Hash matches - No download
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
Downloading:    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

commons-lang3-3.2.1.jar - Started       at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=740, The requested operation requires elevation
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)commons-lang3-3.2.1.jar - Hash matches - No download

        at java.lang.ProcessImpl.start(Unknown Source)
Downloading:    ... 21 more

gson-2.2.4.jar - Started
gson-2.2.4.jar - Hash matches - No download
Downloading:
jopt-simple-4.5.jar - Started
jopt-simple-4.5.jar - Hash matches - No download
Downloading:
jsoup-1.10.3.jar - Started
jsoup-1.10.3.jar - Hash matches - No download
Downloading:
swingx-all-1.6.5.jar - Started
swingx-all-1.6.5.jar - Hash matches - No download
Downloading:
guava-15.0.jar - Started
guava-15.0.jar - Hash matches - No download
Downloading:
log4j-api-2.0-rc2.jar - Started
log4j-api-2.0-rc2.jar - Hash matches - No download
Downloading:
log4j-core-2.0-rc2.jar - Started
log4j-core-2.0-rc2.jar - Hash matches - No download
Downloading:
authlib-1.5.25.jar - Started
authlib-1.5.25.jar - Hash matches - No download
Downloading:
xz-1.4.jar - Started
xz-1.4.jar - Hash matches - No download

`

**Comment by smbarbour** [comment]
So... based on the error message...  the official diagnosis is "Windows is trash.  Launch the command prompt (or Java itself) as administrator and run the bootstrap"

**Comment by Newkz** [comment]
Maybe. In any case, it works when I compile it from Linux, and execute the jar in Windows 10, so that is good enough for me :)
